/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.coco;

public final class R {
    public static final class attr {
    }
    public static final class raw {
        public static final int frag=0x7f020000;
        public static final int test=0x7f020001;
        public static final int vert=0x7f020002;
    }
}
